[versions]
agrona = "2.4.1"
assertj = "3.27.7"
duckdb-jdbc = "1.5.2.0"
eclipse-jdt-core = "3.45.0"
gradle-plugin-publish = "2.1.1"
java-reference-index = "0.1.0"
junit = "6.0.3"
nmcp = "1.4.4"
shadow = "9.3.2"

[libraries]
agrona = { module = "org.agrona:agrona", version.ref = "agrona" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
duckdb-jdbc = { module = "org.duckdb:duckdb_jdbc", version.ref = "duckdb-jdbc" }
eclipse-jdt-core = { module = "org.eclipse.jdt:org.eclipse.jdt.core", version.ref = "eclipse-jdt-core" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
java-reference-index = { id = "io.github.chonghan.java-reference-index", version.ref = "java-reference-index" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
